spring:
  application:
    name: msvc-product
  config:
    import: optional:configserver:http://localhost:8888

jwt:
  secret: ${JWT_SECRET:ClaveSecretaPorDefectoParaDesarrollo}
  expiration: 3600000 # 1 hora
  device-expiration: 1800000000