spring:
  application:
    name: msvc-auth
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    compatibility-verifier:
      enabled: false

jwt:
  secret: ${JWT_SECRET:ClaveSecretaPorDefectoParaDesarrollo}
  expiration: 3600000 # 1 hora
  device-expiration: 1800000000