server:
  port: 8761

spring:
  application:
    name: msvc-eureka
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false #Hace que eureka no se registre así mismo en el servidor
    fetch-registry: false
    server-url:
      defaultZone: http://localhost:${server.port}/eureka