DROP DATABASE IF EXISTS authDb;
DROP DATABASE IF EXISTS userDb;
DROP DATABASE IF EXISTS productDb;
DROP DATABASE IF EXISTS orderDb;

CREATE DATABASE IF NOT EXISTS authDb;
CREATE DATABASE IF NOT EXISTS userDb;
CREATE DATABASE IF NOT EXISTS productDb;
CREATE DATABASE IF NOT EXISTS orderDb;
