server:
  port: 8092

spring:
  application:
    name: msvc-user

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/userDb
    username: root
    password: 12345

  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

  sql:
    init:
      mode: always

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET:ClaveSecretaPorDefectoParaDesarrollo}