server:
  port: 8093

spring:
  application:
    name: msvc-kitchen

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET:ClaveSecretaPorDefectoParaDesarrollo}