server:
  port: 8093

spring:
  application:
    name: msvc-kitchen

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: ${JWT_SECRET:ClaveSecretaPorDefectoParaDesarrollo}