spring:
  application:
    name: msvc-gateway
  config:
    import: optional:configserver:http://config-server:8888

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true